# config.yml
settings:
  concurrency: 50 # Grande vitesse de traitement
  fetchTimeout: 5000 # Temps d'attente augmenté pour la récupération
  linkCheckTimeout: 3000 
  batchSize: 100 
  outputDirPrefix: LiveTV
  channelsPerPage: 99000 # Permet de tout mettre dans un seul fichier sans coupure

urls:
  - https://vavoo.to
