# config.yml
settings:
  concurrency: 60            # Vitesse maximale de traitement simultané
  fetchTimeout: 8000         # Augmentation du délai d'attente pour éviter les coupures
  linkCheckTimeout: 4000     
  batchSize: 150             
  outputDirPrefix: LiveTV
  channelsPerPage: 100000    # Met la totalité absolue des chaînes mondiales dans un seul fichier .m3u

urls:
  - https://vavoo.to
